// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOexJYG7ZiHpdiqu1MCKEwpQefw3J0k_U',
    appId: '1:358358256002:web:b5ee2e6204a5a3fb1b279b',
    messagingSenderId: '358358256002',
    projectId: 'realestate-e97f1',
    authDomain: 'realestate-e97f1.firebaseapp.com',
    storageBucket: 'realestate-e97f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWSYhMIGbbYCkGUeK3gFiNWf8vRx2CGBI',
    appId: '1:358358256002:android:d1a45bc6c4fad66a1b279b',
    messagingSenderId: '358358256002',
    projectId: 'realestate-e97f1',
    storageBucket: 'realestate-e97f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTpwD548iu8W0dCuyWPR_Mz7Ajq8zMyjo',
    appId: '1:358358256002:ios:9fe0509db28eba2a1b279b',
    messagingSenderId: '358358256002',
    projectId: 'realestate-e97f1',
    storageBucket: 'realestate-e97f1.firebasestorage.app',
    iosBundleId: 'com.example.realestateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTpwD548iu8W0dCuyWPR_Mz7Ajq8zMyjo',
    appId: '1:358358256002:ios:9fe0509db28eba2a1b279b',
    messagingSenderId: '358358256002',
    projectId: 'realestate-e97f1',
    storageBucket: 'realestate-e97f1.firebasestorage.app',
    iosBundleId: 'com.example.realestateapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOexJYG7ZiHpdiqu1MCKEwpQefw3J0k_U',
    appId: '1:358358256002:web:f6d235b2179434a91b279b',
    messagingSenderId: '358358256002',
    projectId: 'realestate-e97f1',
    authDomain: 'realestate-e97f1.firebaseapp.com',
    storageBucket: 'realestate-e97f1.firebasestorage.app',
  );
}
